// Bundles the game into dist/game.js (a classic script, so index.html works from file://).
import * as esbuild from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const version = JSON.parse(readFileSync('package.json', 'utf8')).version;

/** The in-game "What's new": each "### New in X" / "### Fixed in X" section of the release notes. */
function releaseNotes(md) {
  const out = [];
  let cur = null;
  for (const line of md.split('\n')) {
    const m = line.match(/^### (New|Fixed) in (\d+\.\d+(?:\.\d+)?)(?::\s*(.*))?$/);
    if (m) { cur = { version: m[2], title: m[3] || (m[1] === 'Fixed' ? 'Fixes' : ''), body: [] }; out.push(cur); continue; }
    if (/^#{1,3} /.test(line)) { cur = null; continue; } // any other heading (Download, Highlights) ends a section
    if (cur) cur.body.push(line);
  }
  return out.map((x) => ({ ...x, body: x.body.join('\n').trim() }));
}
const notes = releaseNotes(readFileSync('docs/RELEASE_NOTES.md', 'utf8'));

const watch = process.argv.includes('--watch');
const options = {
  entryPoints: ['src/main.tsx'],
  bundle: true,
  format: 'iife',
  outfile: 'dist/game.js',
  jsx: 'automatic',
  jsxImportSource: 'preact',
  target: 'es2020',
  minify: !watch,
  sourcemap: watch ? 'inline' : false,
  legalComments: 'none',
  logLevel: 'info',
  define: { __VERSION__: JSON.stringify(version), __NOTES__: JSON.stringify(notes) },
};

// Bundled fonts as data URIs (browsers refuse font files from file:// pages, and the game must work offline).
const LATIN = 'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD';
const LATIN_EXT = 'U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF';
const faces = [
  ['Inter', '100 900', 'inter-latin-ext-wght-normal', LATIN_EXT], ['Inter', '100 900', 'inter-latin-wght-normal', LATIN],
  ...['500', '600', '700'].flatMap((wt) => [['Barlow Condensed', wt, `barlow-condensed-latin-ext-${wt}-normal`, LATIN_EXT], ['Barlow Condensed', wt, `barlow-condensed-latin-${wt}-normal`, LATIN]]),
  ...['600', '700'].flatMap((wt) => [['Cinzel', wt, `cinzel-latin-ext-${wt}-normal`, LATIN_EXT], ['Cinzel', wt, `cinzel-latin-${wt}-normal`, LATIN]]),
];
mkdirSync('dist', { recursive: true });
writeFileSync('dist/fonts.css', '/* Generated by build.mjs from assets/fonts (SIL Open Font License, see assets/fonts/LICENSE.txt). */\n' + faces.map(([family, weight, file, range]) =>
  `@font-face{font-family:'${family}';font-style:normal;font-display:swap;font-weight:${weight};src:url(data:font/woff2;base64,${readFileSync(`assets/fonts/${file}.woff2`).toString('base64')}) format('woff2');unicode-range:${range}}`).join('\n') + '\n');

if (watch) {
  const ctx = await esbuild.context(options);
  await ctx.watch();
  console.log('Watching for changes… open index.html in a browser and refresh after edits.');
} else {
  await esbuild.build(options);
}
