// Clicks through the first tutorial steps in the real UI.
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'playwright');
const b = await chromium.launch();
const page = await b.newPage({ viewport: { width: 1400, height: 950 } });
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
page.on('dialog', (d) => d.accept());
await page.goto('file://' + process.cwd() + '/index.html');
await page.evaluate(() => localStorage.clear());
await page.reload();
await page.click('text=Start campaign');
const nav = (t) => page.click(`.nav button:has-text("${t}")`);
const toast = async () => (await page.$$eval('.toast', (e) => e.map((x) => x.textContent))).slice(-1)[0];
await nav('Employment');
await page.click('button:has-text("Apply") >> nth=0');
console.log('apply:', await toast());
await page.click('button:has-text("Work shift")');
console.log('work:', await toast());
await nav('Character');
await page.click('button:has-text("Train (")');
console.log('train:', await toast());
for (let i = 0; i < 3; i++) await page.click('table button:has-text("+1") >> nth=0');
console.log('attr:', await toast());
await nav('Goods Market');
await page.click('.table button:has-text("Buy") >> nth=0');
console.log('buy:', await toast());
await nav('Inventory');
await page.evaluate(() => { window.meridian.w.citizens[window.meridian.w.playerId].energy = 20; window.meridian.emit(); });
await page.click('button:has-text("Eat") >> nth=0');
console.log('eat:', await toast());
await nav('Currency Market');
await page.click('button:has-text("Buy 1 gold")');
console.log('fx:', await toast());
const tut = await page.evaluate(() => window.meridian.w.player.tutorial);
console.log('tutorial step reached:', tut, '(7 = next is join a party)');
await nav('Dashboard');
await page.screenshot({ path: 'build/shots/play-dashboard.png', fullPage: true });
console.log('errors:', errors.length ? errors : 'none');
await b.close();
