// Source definitions for the Earth map. `node tools/build-earth.mjs` turns these
// into src/data/earth.json (projected region shapes, label points and links).
//
// Each playable nation is a real country (ISO 3166 numeric id as used by the
// world-atlas data). Regions are approximate groupings of states/provinces:
// the builder splits each country with a Voronoi diagram around the listed
// centres ([lon, lat]) and clips it to the real border, so boundaries between
// regions of one country are approximate. Terrain and resource lists are
// hand-picked flavour (SOLO); richness is rolled per world seed.
//
// leader/legislature are display titles only: every nation uses the same
// election, congress and cabinet rules.

export const NATIONS = [
  { iso: '840', code: 'USA', name: 'United States', adj: 'American', color: '#3f6fd8', cur: 'USD', leader: 'President', legislature: 'Congress',
    regions: [
      ['Mid-Atlantic', -77.5, 39.6, 'plains', ['grain'], true],
      ['New England', -71.5, 43.8, 'forest', ['iron']],
      ['Southeast', -84, 32.5, 'forest', ['grain']],
      ['Great Lakes', -86, 42.5, 'plains', ['iron', 'grain']],
      ['Great Plains', -98, 41.5, 'plains', ['grain']],
      ['Texas', -99, 31, 'desert', ['oil']],
      ['Mountain West', -109, 40.5, 'mountains', ['titanium', 'iron']],
      ['California', -119.5, 36.5, 'plains', ['grain', 'oil']],
      ['Pacific Northwest', -120.5, 46, 'forest', ['grain']],
      ['Alaska', -150, 64, 'mountains', ['oil'], false, [[-134, 57.5], [-160, 58]]],
    ] },
  { iso: '124', code: 'CAN', name: 'Canada', adj: 'Canadian', color: '#e06666', cur: 'CAD', leader: 'Prime Minister', legislature: 'Parliament',
    regions: [
      ['Ontario', -84, 49.5, 'forest', ['iron'], true],
      ['Quebec', -72, 52, 'forest', ['titanium']],
      ['Maritimes', -63.5, 46.5, 'forest', ['grain']],
      ['Prairies', -106, 53, 'plains', ['grain', 'oil']],
      ['British Columbia', -124, 54, 'mountains', ['titanium']],
      ['Northwest Territories', -120, 64, 'forest', ['oil']],
      ['Nunavut', -88, 68, 'mountains', ['iron']],
    ] },
  { iso: '484', code: 'MEX', name: 'Mexico', adj: 'Mexican', color: '#3fa672', cur: 'MXN', leader: 'President', legislature: 'Congress of the Union',
    regions: [
      ['Central Mexico', -99.1, 19.8, 'plains', ['grain'], true],
      ['Northern Mexico', -105, 28, 'desert', ['iron']],
      ['Baja California', -114, 29, 'desert', ['titanium']],
      ['Western Mexico', -103.5, 21.8, 'mountains', ['grain']],
      ['Gulf & Yucatán', -91, 18.5, 'forest', ['oil']],
    ] },
  { iso: '076', code: 'BRA', name: 'Brazil', adj: 'Brazilian', color: '#d8c43a', cur: 'BRL', leader: 'President', legislature: 'National Congress',
    regions: [
      ['Central-West', -50, -14, 'plains', ['grain'], true],
      ['Amazonas', -64, -4, 'forest', ['titanium']],
      ['Pará', -52, -4, 'forest', ['iron']],
      ['Northeast', -40, -8, 'plains', ['grain']],
      ['Southeast', -45, -20, 'mountains', ['iron', 'oil']],
      ['South', -52, -27, 'plains', ['grain']],
    ] },
  { iso: '032', code: 'ARG', name: 'Argentina', adj: 'Argentine', color: '#74b9e8', cur: 'ARS', leader: 'President', legislature: 'National Congress',
    regions: [
      ['Buenos Aires', -60, -35, 'plains', ['grain'], true],
      ['Cuyo', -68, -32, 'mountains', ['titanium']],
      ['Northern Argentina', -63, -26, 'forest', ['grain', 'iron']],
      ['Patagonia', -69, -45, 'desert', ['oil']],
    ] },
  { iso: '826', code: 'GBR', name: 'United Kingdom', adj: 'British', color: '#8a63d2', cur: 'GBP', leader: 'Prime Minister', legislature: 'Parliament',
    regions: [
      ['London & South East', -0.8, 51.5, 'plains', ['grain'], true],
      ['Northern England', -1.8, 54.1, 'plains', ['iron']],
      ['Wales', -3.8, 52.3, 'mountains', ['iron']],
      ['Scotland', -4.3, 57, 'mountains', ['oil']],
      ['Northern Ireland', -6.7, 54.6, 'plains', ['grain']],
    ] },
  { iso: '276', code: 'DEU', name: 'Germany', adj: 'German', color: '#7e8a4a', cur: 'EUR', leader: 'Chancellor', legislature: 'Bundestag',
    regions: [
      ['Berlin-Brandenburg', 13.3, 52.6, 'plains', ['grain'], true],
      ['Saxony', 13.3, 51, 'mountains', ['iron']],
      ['Bavaria', 11.4, 48.9, 'mountains', ['titanium']],
      ['Baden-Württemberg', 8.9, 48.5, 'forest', ['grain']],
      ['Rhineland', 7.1, 50.9, 'plains', ['iron']],
      ['Northern Germany', 9.6, 53.3, 'plains', ['grain', 'oil']],
    ] },
  { iso: '643', code: 'RUS', name: 'Russia', adj: 'Russian', color: '#a0785a', cur: 'RUB', leader: 'President', legislature: 'State Duma',
    regions: [
      ['Central Russia', 38, 55, 'plains', ['grain'], true],
      ['Northwest Russia', 34, 62.5, 'forest', ['iron']],
      ['Volga', 47, 54, 'plains', ['grain', 'oil']],
      ['Southern Russia', 42, 46, 'plains', ['grain']],
      ['Ural', 60, 58, 'mountains', ['iron', 'titanium']],
      ['West Siberia', 75, 60, 'forest', ['oil']],
      ['East Siberia', 105, 60, 'forest', ['iron']],
      ['Russian Far East', 135, 55, 'forest', ['titanium']],
      ['Chukotka', 165, 66, 'mountains', ['oil']],
    ] },
  { iso: '792', code: 'TUR', name: 'Turkey', adj: 'Turkish', color: '#d9663a', cur: 'TRY', leader: 'President', legislature: 'Grand National Assembly',
    regions: [
      ['Central Anatolia', 33, 39, 'plains', ['grain'], true],
      ['Marmara', 28.5, 40.8, 'plains', ['grain']],
      ['Aegean', 28, 38.3, 'plains', ['iron']],
      ['Black Sea Coast', 37, 41, 'forest', ['titanium']],
      ['Eastern Anatolia', 41.5, 39.3, 'mountains', ['iron']],
      ['Southeast Anatolia', 39.5, 37.4, 'desert', ['oil']],
    ] },
  { iso: '682', code: 'SAU', name: 'Saudi Arabia', adj: 'Saudi', color: '#1d6b50', cur: 'SAR', leader: 'Prime Minister', legislature: 'Consultative Assembly',
    regions: [
      ['Riyadh', 45.5, 24.5, 'desert', ['oil', 'grain'], true],
      ['Eastern Province', 51, 22.5, 'desert', ['oil']],
      ['Hejaz', 39.5, 23, 'desert', ['grain']],
      ['Asir', 43, 18.5, 'mountains', ['iron']],
      ['Northern Borders', 41, 29.5, 'desert', ['titanium']],
    ] },
  { iso: '710', code: 'ZAF', name: 'South Africa', adj: 'South African', color: '#3fb3a8', cur: 'ZAR', leader: 'President', legislature: 'Parliament',
    regions: [
      ['Gauteng', 28, -26.2, 'plains', ['iron'], true],
      ['Western Cape', 20, -33.4, 'plains', ['grain']],
      ['Eastern Cape', 26.5, -32.2, 'plains', ['grain']],
      ['KwaZulu-Natal', 30.8, -28.8, 'forest', ['titanium']],
      ['Northern Cape', 21, -29, 'desert', ['iron']],
      ['Limpopo', 29.5, -23.5, 'plains', ['grain']],
    ] },
  { iso: '356', code: 'IND', name: 'India', adj: 'Indian', color: '#f0a040', cur: 'INR', leader: 'Prime Minister', legislature: 'Lok Sabha',
    regions: [
      ['Delhi & Punjab', 76, 29.8, 'plains', ['grain'], true],
      ['Gangetic Plain', 81, 26.5, 'plains', ['grain']],
      ['East India', 86, 23, 'forest', ['iron']],
      ['Northeast India', 93, 26, 'forest', ['oil']],
      ['Maharashtra', 75.5, 19, 'plains', ['grain']],
      ['Gujarat', 71.5, 22.5, 'desert', ['oil']],
      ['South India', 78, 12, 'plains', ['titanium']],
      ['Rajasthan', 73, 27, 'desert', ['iron']],
      ['Kashmir', 76, 34, 'mountains', ['titanium']],
    ] },
  { iso: '156', code: 'CHN', name: 'China', adj: 'Chinese', color: '#c9303c', cur: 'CNY', leader: 'President', legislature: 'National People’s Congress',
    regions: [
      ['North China', 115, 38.5, 'plains', ['grain', 'iron'], true],
      ['Manchuria', 126, 46, 'plains', ['grain', 'oil']],
      ['East China', 119, 32.5, 'plains', ['grain']],
      ['South China', 113, 23.5, 'forest', ['grain']],
      ['Central China', 112, 29.5, 'plains', ['iron']],
      ['Sichuan', 104, 30.5, 'mountains', ['grain']],
      ['Yunnan', 101, 25, 'mountains', ['titanium']],
      ['Xinjiang', 85, 41, 'desert', ['oil']],
      ['Tibet', 89, 32, 'mountains', ['titanium']],
      ['Inner Mongolia', 111, 42.5, 'plains', ['iron']],
    ] },
  { iso: '392', code: 'JPN', name: 'Japan', adj: 'Japanese', color: '#e87fb0', cur: 'JPY', leader: 'Prime Minister', legislature: 'National Diet',
    regions: [
      ['Kantō', 139.7, 36, 'plains', ['grain'], true],
      ['Kansai', 135.5, 34.9, 'plains', ['iron']],
      ['Hokkaidō', 143, 43.3, 'forest', ['grain']],
      ['Kyūshū', 131, 32.5, 'mountains', ['titanium']],
      ['Tōhoku', 140.5, 39.5, 'forest', ['grain']],
    ] },
  { iso: '410', code: 'KOR', name: 'South Korea', adj: 'Korean', color: '#5b7fa8', cur: 'KRW', leader: 'President', legislature: 'National Assembly',
    regions: [
      ['Seoul Capital Area', 126.9, 37.4, 'plains', ['grain'], true],
      ['Gangwon', 128.5, 37.6, 'mountains', ['titanium']],
      ['Chungcheong', 127.2, 36.5, 'plains', ['grain']],
      ['Gyeongsang', 128.8, 35.7, 'mountains', ['iron']],
      ['Jeolla', 126.9, 35, 'plains', ['grain']],
    ] },
  { iso: '036', code: 'AUS', name: 'Australia', adj: 'Australian', color: '#c28a2e', cur: 'AUD', leader: 'Prime Minister', legislature: 'Parliament',
    regions: [
      ['New South Wales', 147, -32.5, 'plains', ['grain'], true],
      ['Victoria', 144.5, -37, 'plains', ['grain']],
      ['Queensland', 145, -22, 'forest', ['oil']],
      ['South Australia', 135, -30, 'desert', ['titanium']],
      ['Western Australia', 122, -26, 'desert', ['iron']],
      ['Northern Territory', 133, -19, 'desert', ['iron']],
      ['Tasmania', 146.5, -42, 'forest', ['titanium']],
    ] },
];

// Sea lanes and overland corridors through neutral countries: extra links so
// every nation can be reached, supplied and (by naval landing) attacked.
export const ROUTES = [
  ['United Kingdom/London & South East', 'Germany/Northern Germany', 'North Sea'],
  ['United Kingdom/Scotland', 'Canada/Maritimes', 'North Atlantic'],
  ['United Kingdom/London & South East', 'United States/New England', 'North Atlantic'],
  ['Germany/Northern Germany', 'Russia/Northwest Russia', 'Baltic Sea'],
  ['Germany/Bavaria', 'Turkey/Marmara', 'Danube corridor'],
  ['Russia/Southern Russia', 'Turkey/Black Sea Coast', 'Black Sea'],
  ['Turkey/Southeast Anatolia', 'Saudi Arabia/Northern Borders', 'Mesopotamian corridor'],
  ['Saudi Arabia/Eastern Province', 'India/Gujarat', 'Arabian Sea'],
  ['Saudi Arabia/Asir', 'South Africa/KwaZulu-Natal', 'Indian Ocean'],
  ['South Africa/Western Cape', 'Brazil/Southeast', 'South Atlantic'],
  ['South Africa/KwaZulu-Natal', 'Australia/Western Australia', 'Indian Ocean'],
  ['Mexico/Gulf & Yucatán', 'Brazil/Amazonas', 'Caribbean'],
  ['United States/Southeast', 'Brazil/Northeast', 'Atlantic'],
  ['United States/California', 'Japan/Kantō', 'Pacific'],
  ['United States/Alaska', 'Russia/Chukotka', 'Bering Strait'],
  ['Russia/Russian Far East', 'Japan/Hokkaidō', 'Sea of Japan'],
  ['China/East China', 'South Korea/Seoul Capital Area', 'Yellow Sea'],
  ['South Korea/Gyeongsang', 'Japan/Kyūshū', 'Korea Strait'],
  ['China/East China', 'Japan/Kyūshū', 'East China Sea'],
  ['Australia/Northern Territory', 'China/South China', 'South China Sea'],
  ['Australia/Queensland', 'Japan/Kyūshū', 'Western Pacific'],
  ['India/South India', 'Australia/Western Australia', 'Indian Ocean'],
];
