// Earth map data, generated by tools/build-earth.mjs from Natural Earth shapes
// (via world-atlas, public domain) and tools/earth-defs.mjs. Region order here is
// the region id order in every world. Shapes stay out of saves.
import raw from './earth.json';
import type { RawRes, Terrain } from '../sim/types';

export interface EarthNation { name: string; code: string; label: [number, number]; span: number; adj: string; color: string; cur: string; iso: string; leader: string; legislature: string }
export interface EarthRegion { name: string; nation: number; capital: boolean; terrain: Terrain; res: RawRes[]; x: number; y: number; span: number; path: string; links: number[] }
export interface EarthRoute { a: number; b: number; name: string }

export const EARTH = raw as unknown as {
  width: number; height: number; background: string; graticule: string;
  nations: EarthNation[]; regions: EarthRegion[]; routes: EarthRoute[];
};
