// Earth map data, generated by tools/build-earth.mjs from Natural Earth 1:10m data
// (public domain) and tools/earth-defs.mjs. Region order here is
// the region id order in every world. Shapes stay out of saves.
import raw from './earth.json';
import type { RawRes, Terrain } from '../sim/types';

export interface EarthNation { name: string; code: string; label: [number, number]; span: number; adj: string; color: string; cur: string; iso: string; leader: string; legislature: string; capital: number; pop: number }
/** Regional government template (real titles; 'appointed' where the national government names the head). */
export interface EarthGov { title: string; legislature: string; mode: 'elected' | 'appointed' }
export interface EarthRegion {
  name: string; nation: number; kind: string; seat: string; city: string; gov: EarthGov | null; noWageTax?: boolean;
  seas?: string[]; // sea zones this region's coast touches
  terrain: Terrain; res: RawRes[]; popReal: number; x: number; y: number; lon: number; lat: number; span: number; path: string; links: number[];
}
export interface EarthRoute { a: number; b: number; name: string }

export const EARTH = raw as unknown as {
  width: number; height: number; background: string; lakes: string; nationBorders: string; graticule: string;
  nations: EarthNation[]; regions: EarthRegion[]; routes: EarthRoute[];
  seas: { name: string; x: number; y: number; adj: string[] }[];
};
